 // WRITE YOUR TEST CASES IN THIS FILE.
 // OUTPUT OF EACH FUNCTION MUST BE WRITTEN AT THE END OF THE CORRESPONDING FUNCTION IN CODE COMMENTS.
 // OUTPUT MUST BE WRITTEN IN THE PRESCRIBED FORMAT ONLY.
